### ISSUE TITLE
There is pony town an api?

### ISSUE THREAD

**Issue by princess-of-the-backrooms** [drewdru/ponyTown#1]
Hello, pony town devs!~
I'm Daisy, a front-end javascript dev. I've a question: there is a api for ponytown (like a api to get informations, how server or a client)? Is it public for devs' use? I Hope you reply me soon!~
                      - With respect, Daisy

**Comment by Daisyzinha** [comment]
.

**Comment by drewdru** [comment]
Hi. I'm not a developer of Pony Town, this repository is just a fork. They previously published this project on their website with a LICENSE that allows to edit and distribute their code and all other files in this repository.
You can find developers contacts here: https://pony.town/about

Please read the license files to know more about what you can do with this repository: [LICENSE_MUSIC](https://github.com/drewdru/ponyTown/blob/master/LICENSE_MUSIC.txt), [LICENSE_ART](https://github.com/drewdru/ponyTown/blob/master/LICENSE_ART.txt), and [LICENSE_CODE](https://github.com/drewdru/ponyTown/blob/master/LICENSE_CODE.txt)
